VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"
  config.vm.network "private_network", ip: "192.168.55.44"

  config.vm.synced_folder "./", "/opt/foo", type: 'nfs'
  config.vm.network "forwarded_port", guest: 5858, host: 5858

  config.vm.provider "virtualbox" do |vb|
     vb.customize ["modifyvm", :id, "--memory", "4096", '--cpus', '3']
  end

  config.vm.provision :shell, :path => "./provision/gogo.sh"

end